name: a_commerce
description: A simple E-Commerce App for flutter using firebase.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  # Firebase Dependencies
  firebase_core: "0.5.0"
  firebase_auth: "^0.18.0+1"
  cloud_firestore: "^0.14.0+2"

  # Google Fonts
  google_fonts: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
     - assets/images/